name: 'Radiant Synthesis'
description: 'Run Radiant Synthesis'
inputs:
  RDF:
    description: 'path to rdf file'
    required: true

runs:
  using: "composite"
  steps:
    - run: pnmainc ${{ github.action_path }}/radiant/radiant_synthesis.tcl $RDF
      shell: bash
