name: 'Radiant Full Compilation'
description: 'Run Radiant Full Full Compilation'
inputs:
  RDF:
    description: 'path to rdf file'
    required: true

runs:
  using: "composite"
  steps:
    - name: Radiant Synthesis
      uses: sweehualaw/radiant_synthesis@v2
      with:
        RDF: ${{ inputs.RDF }}
    - name: 'Radiant Map'
      uses: sweehualaw/radiant_map@v2
      with:
        RDF: ${{ inputs.RDF }}
    - name: 'Radiant PAR'
      uses: sweehualaw/radiant_par@v2
      with:
        RDF: ${{ inputs.RDF }}
    - name: 'Radiant export'
      uses: sweehualaw/radiant_export@v2
      with:
        RDF: ${{ inputs.RDF }}
